"""Regenerate the plugin's knowledge/ files from the live report configs.

The plugin ships two generated docs. Both drift the moment a config is added or
renamed, which is exactly what happened when CAMPAIGN_LOOKUP / MERCHANT_LOOKUP were
authored — reports.md had been produced by a one-off inline script and silently went
stale. Hence this file: regenerate, never hand-edit.

  knowledge/reports.md   the report catalogue the agent consults for columns + caveats
  knowledge/tool-map.md  legacy ADK tool name -> report, columns, required filters

Usage:  python3 scripts/build_plugin_knowledge.py [--plugin PATH] [--check]

--check exits non-zero if the generated output differs from what is on disk, so CI (or
you, before a PR) can catch drift instead of discovering it in review.
"""

import argparse
import difflib
import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, ".."))
CONFIGS = os.path.join(REPO, "kam_report_configs")
# Where the marketplace checkout lives. Override with OSMOS_CLAUDE_PLUGINS when your
# clone sits somewhere else; if the path is absent we generate into this repo only,
# rather than failing, so `--check` still works without the second checkout.
PLUGINS_REPO = os.environ.get(
    "OSMOS_CLAUDE_PLUGINS",
    os.path.join(os.path.expanduser("~"), "Desktop", "osmos-claude-plugins"),
)
DEFAULT_PLUGIN = os.path.join(
    PLUGINS_REPO, "plugins", "analytics", "core", "data-analysis-agent"
)
# Both consumers get the same generated docs. The agent repo is where the SOPs are
# developed and tested; the plugin is what ships. `common-rules.md` sends the agent to
# knowledge/tool-map.md, so a repo missing it silently breaks the tool-binding gate.
OUTPUT_ROOTS = ([DEFAULT_PLUGIN] if os.path.isdir(DEFAULT_PLUGIN) else []) + [REPO]
if len(OUTPUT_ROOTS) == 1:
    print(f"[warn] plugin checkout not found at {DEFAULT_PLUGIN} — writing to this repo "
          f"only. Set OSMOS_CLAUDE_PLUGINS to keep both in sync.", file=sys.stderr)

BLOCKED = {"AUDIT_EVENTS_REPORT", "CATEGORY_REQUEST_VOLUME_REPORT", "FILTER_PRESENCE_RR_REPORT"}
# Columns that cannot be requested as attributes, with the reason.
UNREQUESTABLE = {
    "RR_DISPLAY_REPORT": ("store_id", "the Display facts table has no such column"),
}


def active_configs():
    out = []
    for p in sorted(glob.glob(os.path.join(CONFIGS, "*", "*.json"))):
        if os.path.basename(os.path.dirname(p)) == "_retired":
            continue
        out.append(json.load(open(p)))
    return out


def verify_status():
    """Fetch-verification verdicts, if a run exists. Absent = unknown, not 'fine'."""
    p = os.path.join(HERE, "out", "verify_remaining.json")
    if not os.path.exists(p):
        return {}
    return {r["reportType"]: r["verdict"] for r in json.load(open(p))}


def build_reports_md(cfgs, status, merged):
    def mark(d):
        rt, ext = d["reportType"], d.get("externalReportType")
        if ext in BLOCKED:
            return "⛔ blocked"
        if rt in merged:
            return "✅"
        return {"OK": "✅", "EMPTY": "⚠️ 0 rows", "ERROR": "⛔ error"}.get(status.get(rt), "—")

    L = []
    L.append("""# KAM report catalogue

The reports behind this plugin's skills. You request **columns** — the SQL is frozen in a
reviewed template, so a caller chooses *which columns, which dates, which filters*, never
*which SQL*.

Served from `/osmosReportingMcp/internalPerformance`.

> Generated by `scripts/build_plugin_knowledge.py` in the `osmos-data-analysis-agent`
> repo. **Do not hand-edit** — regenerate, or it drifts from the deployed configs.

## Calling a report

```
run_report(reportType=<external name>, attributes=[...], metrics=[...],
           dateRanges=[{startDate, endDate}], filters=[...])
```

- You group by whatever attributes you request. **A report declaring 13 attributes is a
  menu, not a 13-column report.**
- Requesting **no** attributes returns the ungrouped total — only for reports marked
  *ungrouped*; the others need at least one.
- **Required filters are enforced by the MCP** (`run_report.py`), and with AND semantics:
  every listed filter must be supplied.
- Comparisons are **two calls**. These reports are single-period and emit no
  `_prev` / `_change` / `_perc` variants.

Legend: ✅ verified · ⚠️ sound but no data in the test window · ⛔ see Known issues · — untested
""")
    groups = {}
    for d in cfgs:
        for t in (d.get("filterTags") or ["(untagged)"]):
            groups.setdefault(t.replace("report_group:", ""), []).append(d)

    for g in sorted(groups):
        L.append(f"\n## {g}\n")
        L.append("| Report | Required filters | Attrs | Metrics | |")
        L.append("|---|---|---|---|---|")
        for d in sorted(groups[g], key=lambda x: x.get("externalReportType") or ""):
            req = ", ".join(f"`{r}`" for r in (d.get("externalRequiredFilters") or [])) or "—"
            ung = "" if "__ATTRIBUTES__" in (d.get("query") or {}).get("REPORTING", "") else " *(ungrouped)*"
            L.append(f"| `{d.get('externalReportType')}`{ung} | {req} | "
                     f"{len(d.get('attributes') or {})} | {len(d.get('metrics') or {})} | {mark(d)} |")

    L.append("""
---

## Known issues

| Report | Issue | What to do |
|---|---|---|
| `AUDIT_EVENTS_REPORT` · `FILTER_PRESENCE_RR_REPORT` | their configs name appKey `GCP_BQ_KAM_CREDENTIALS_EXTERNAL_DATASET`, which is **not registered in kamService** — they fail at BQ client init | unavailable; needs a kamService change |
| `CATEGORY_REQUEST_VOLUME_REPORT` | reaches BigQuery but is **Access Denied** on `reporting_<region>.os_product_ads_request_report` | unavailable; needs a BQ grant |
| `DAILY_ORDER_TRENDS_REPORT` | `channel` removed — it selected `cvcpf.channel`, unbound in the outer query, and cannot be exposed without inflating the site metrics | no PLA/Display split here; use `MERCHANT_PERFORMANCE_REPORT` |
| `RESPONDED_SKUS_REPORT` | declares `perf_keyword` required, but **kamService does not enforce `externalRequiredFilters`** — an unscoped fetch runs and never returns | **always scope by `keyword`**; the MCP applies it, direct callers must too |
| `RESPONDED_SKUS_REPORT` | `perf_campaign_id` renamed to `perf_internal_campaign_id` — it holds the internal id, not the marketing id in the UI | filter with the internal id (from `CAMPAIGN_LOOKUP_REPORT`); the two are not 1:1 |
| `GMV_ATTRIBUTION_REPORT` | `channel` removed — the template is ungrouped (no attributes slot) | request no attributes; it returns one total row |
| `RR_DISPLAY_REPORT` | no `store_id` — the Display facts table lacks the column | use `RR_PLA_REPORT` for store-level RR |
| `CAMPAIGN_LOOKUP_REPORT` · `MERCHANT_LOOKUP_REPORT` | resolve an entity from **any one of** several id keys, so they deliberately declare no required filter | pass whichever id you hold |

## Verification state

Reports were fetched against agency 105 (takealot-marketplace, ZAR) for 2026-07-19→21
requesting every exposed column. The 15 consolidated reports were additionally diffed
row-by-row against the 42 they replaced: **39/39 runnable pairs identical** — zero rows
lost, zero gained, zero drift.

Untested: `is_negative` on `CAMPAIGN_KEYWORDS_REPORT` (no test campaign has keywords) and
`attributed_sales` (0.00 on every keyword row in the window).
""")
    return "\n".join(L) + "\n"



# ── tool-map.md ───────────────────────────────────────────────────────────────
# The SOPs still name the legacy ADK functions. This table is what binds those
# names to the reports that replaced them, so it MUST regenerate whenever a config
# changes — it was previously built by a one-off script and went stale silently.

STATE_TOOLS = [
    ("get_context",            "the intake already established it in this conversation"),
    ("update_context",         "hold it in the conversation"),
    ("get_date_ranges",        "the dates resolved during intake"),
    ("get_today",              "you know the date"),
    ("get_all_findings",       "your own earlier turns"),
    ("update_analysis",        "your own narration; present a checkpoint instead"),
    ("get_discoveries",        "your own earlier turns"),
    ("store_agent_findings",   "state the finding in your summary"),
    ("get_keyword_categories", "no equivalent — say so rather than inventing one"),
]

# Filters a caller must now pass, because the merged template dropped a guard that
# only some family members carried. Keyed by the RETIRED reportType.
MIGRATION = {
    "INTERNAL_PERF_MERCHANT_KEYWORD":
        "`perf_campaign_type` = 'performance' + `perf_campaign_subtype` IN (os_ads_search, smart_shopping)",
    "INTERNAL_PERF_CAMPAIGN_PERF_DAILY":
        "`perf_campaign_type` IN (PERFORMANCE, INVENTORY, OFFSITE); group by `perf_date`",
    "INTERNAL_PERF_CAMPAIGN_KW_TARGETED":  "`perf_is_negative` = 0",
    "INTERNAL_PERF_CAMPAIGN_KW_NEGATIVE":  "`perf_is_negative` = 1",
    "INTERNAL_PERF_BUDGET_CHANGES":        "`perf_action_type_id` = 17",
    "INTERNAL_PERF_CAMPAIGN_STATUS_CHANGES": "`perf_action_type_id` = 16",
    "INTERNAL_PERF_PRODUCT_SELECTION_CHANGES": "`perf_action_type_id` IN (50, 51)",
    "INTERNAL_PERF_RR_DISPLAY_PAGE_TYPE":  "`perf_page_type` NOT IN ('', 'NA')",
    "INTERNAL_PERF_RR_BY_PAGE_DISPLAY":    "`perf_page_type` NOT IN ('', 'NA')",
    "INTERNAL_PERF_BU_REQUESTS_DISPLAY":   "`perf_page_type` NOT IN ('', 'NA'); group by `perf_date`",
    "INTERNAL_PERF_BU_REQUESTS_PLA":       "group by `perf_date`",
    "INTERNAL_PERF_RR_HOURLY":             "group by `perf_hour`",
    "INTERNAL_PERF_RR_HOURLY_AD_UNIT":     "group by `perf_ad_unit`",
    "INTERNAL_PERF_STORE_LEVEL_RR":        "group by `perf_store_id`, `perf_category`, `perf_day`, `perf_hour`",
    "INTERNAL_PERF_KW_REQUEST_VOLUME":     "request `perf_days_with_requests`",
    "INTERNAL_PERF_CATEGORY_RR":           "`perf_category_l1` != '' + `perf_page_type` NOT IN ('', 'NA')",
    "INTERNAL_PERF_MERCHANT_CATEGORY_CPC": "use `perf_category_l1_raw` / `_l2_raw` / `_l3_raw`",
    "INTERNAL_PERF_CAMPAIGN_NETWORKS_BY_ID": "filter `perf_internal_campaign_id` (not `perf_campaign_id`)",
}


def build_tool_map():
    """legacy ADK tool name -> report, columns, required filters."""
    import re
    import build_query_report_matrix as M
    from merge_lib import load

    skills = sorted(glob.glob(os.path.join(REPO, ".claude", "skills", "*", "SKILL.md")))
    txt = "".join(open(f).read() for f in skills)
    names = sorted(set(re.findall(
        r"`(get_[a-z_0-9]+|check_[a-z_0-9]+|fetch_[a-z_0-9]+|lookup_[a-z_0-9]+)"
        r"(?:\([^`]*\))?`", txt)))   # SOPs write some calls with args inside the backticks
    state = {n for n, _ in STATE_TOOLS}

    queries = [M.parse_sql(p) for p in sorted(M.QUERY_DIR.glob("*/*.sql"))]
    active = [c for p in sorted(M.CONFIG_DIR.glob("*/*.json"))
              if p.parent.name != "_retired" and (c := M.parse_config(p))]
    serving = {}
    for cfg in active:
        for claim in M.match(cfg, queries)[0]:
            serving.setdefault(claim, []).append(cfg)

    pred = {}
    for wave in ("merge_wave1", "merge_wave2", "merge_wave3"):
        for spec in __import__(wave).SPECS:
            for old_rel in spec["absorbs"]:
                if old_rel == spec["path"]:
                    continue
                old = load(old_rel)
                for claim in M.match({"reportType": old["reportType"],
                                      "skill": old_rel.split("/")[0]}, queries)[0]:
                    pred[(claim[0], claim[1], spec["reportType"])] = old

    L = ["""# Legacy tool name → report map

The `debug-*` SOPs were extracted from the Google-ADK agent and still name **its Python
functions** (`check_gmv_attribution`, `get_merchant_breakdown`, …). **Those tools do not
exist here.**

Every data call is `run_report`. When a SOP names one of the identifiers below, resolve it
through this table first.

> Generated by `scripts/build_plugin_knowledge.py`. **Do not hand-edit.**

```
run_report(reportType=<Report>, attributes=[...], metrics=[...],
           dateRanges=[{startDate, endDate}], filters=[...])
```

- **"In comparison mode" = two calls.** Single-period reports, no `_prev` variants.
- **Request only the columns the step needs.** The `Request` column is a starting set.
- **"must pass" is not optional** — it replaces a hardcoded `WHERE` the retired report had.
- **Every external column is `perf_`-prefixed.** Never guess a name; take it from here.
- One legacy name can map to **more than one report** (the PLA / Display splits).

Full column lists and known issues: `knowledge/reports.md`.

---

## Data tools
""", "| Legacy name | Report | Request | Notes |", "|---|---|---|---|"]

    for n in names:
        if n in state:
            continue
        stems = [q for q in queries if q["stem"] == n or q["stem"].startswith(n + "__")]
        if not stems:
            L.append(f"| `{n}` | — | — | no extracted query — verify this call still exists |")
            continue
        for q in stems:
            cfgs = serving.get((q["skill"], q["stem"]), [])
            if not cfgs:
                L.append(f"| `{n}` | — | — | **no report serves this yet** |")
                continue
            for cfg in cfgs:
                full = json.loads(cfg["config"])
                rt, ext = full["reportType"], full.get("externalReportType")
                p = pred.get((q["skill"], q["stem"], rt))
                # Column NAMES must come from the LIVE config — retired configs in
                # _retired/ were never renamed, so sourcing names from a predecessor
                # would tell the agent to request columns that no longer exist. Use the
                # predecessor only to decide WHICH columns that legacy call needed, then
                # resolve each to its current name via the live config.
                skip = {c for c, _ in [UNREQUESTABLE.get(ext, (None, None))] if c}
                live = {sec: {c.get("externalColumnName") for c in (full.get(sec) or {}).values()
                              if c.get("externalColumnName")}
                        for sec in ("attributes", "metrics")}

                def resolve(name, sec):
                    """old external name -> its current name on the live report."""
                    for cand in (name, "perf_" + name):
                        if cand in live[sec]:
                            return cand
                    return None

                src = p or full
                # NB: no walrus here — `:=` inside a comprehension leaks into the
                # enclosing scope and would clobber the loop variable `n`.
                attrs, mets = [], []
                for c in (src.get("attributes") or {}).values():
                    r = resolve(c.get("externalColumnName") or "", "attributes")
                    if r and r not in skip:
                        attrs.append(r)
                for c in (src.get("metrics") or {}).values():
                    r = resolve(c.get("externalColumnName") or "", "metrics")
                    if r and not r.endswith("placeholder_metric"):
                        mets.append(r)
                note = []
                if p and p["reportType"] in MIGRATION:
                    note.append("**must pass:** " + MIGRATION[p["reportType"]])
                if full.get("externalRequiredFilters"):
                    note.append("required: " + ", ".join(f"`{x}`" for x in full["externalRequiredFilters"]))
                if ext in BLOCKED:
                    note.append("⛔ **unavailable** — see reports.md")
                if ext in UNREQUESTABLE:
                    col, why = UNREQUESTABLE[ext]
                    note.append(f"⚠️ `{col}` not requestable — {why}")
                variant = q["stem"][len(n) + 2:] if q["stem"].startswith(n + "__") else ""
                label = n + (f" ({variant})" if variant else "")
                req = ("attrs: " + ", ".join(f"`{x}`" for x in attrs[:6]) + (" …" if len(attrs) > 6 else "")
                       ) if attrs else "attrs: *(none — ungrouped)*"
                req += "<br>" + (("metrics: " + ", ".join(f"`{x}`" for x in mets[:6])
                                  + (" …" if len(mets) > 6 else "")) if mets else "metrics: —")
                L.append(f"| `{label}` | `{ext}` | {req} | {' · '.join(note) or '—'} |")

    L.append("""
---

## State tools — do not look for a replacement

The ADK agent kept context in a session-state store because its sub-agents could not see
the conversation. **There is no state store here.**

| Legacy name | Use instead |
|---|---|""")
    for n, use in STATE_TOOLS:
        L.append(f"| `{n}` | {use} |")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--plugin", default=DEFAULT_PLUGIN)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    sys.path.insert(0, HERE)
    merged = {s["reportType"] for w in ("merge_wave1", "merge_wave2", "merge_wave3")
              for s in __import__(w).SPECS}
    cfgs = active_configs()
    docs = {"reports.md":  build_reports_md(cfgs, verify_status(), merged),
            "tool-map.md": build_tool_map()}

    roots = [a.plugin, REPO] if a.plugin == DEFAULT_PLUGIN else [a.plugin]
    drift = 0
    for root in roots:
        for fname, new in docs.items():
            target = os.path.join(root, "knowledge", fname)
            old = open(target).read() if os.path.exists(target) else ""
            if a.check:
                if old == new:
                    print(f"ok    {target}")
                else:
                    drift = 1
                    print(f"DRIFT {target}" + ("  (missing)" if not old else ""))
                    sys.stdout.writelines(difflib.unified_diff(
                        old.splitlines(True), new.splitlines(True), "on disk", "generated", n=1))
                continue
            os.makedirs(os.path.dirname(target), exist_ok=True)
            open(target, "w").write(new)
            print(f"wrote {target}")
    if a.check:
        return drift
    print(f"  {len(cfgs)} active configs, "
          f"{sum(1 for c in cfgs if c.get('externalReportType') in BLOCKED)} blocked")
    return 0


if __name__ == "__main__":
    sys.exit(main())
