"""Move superseded configs to kam_report_configs/_retired/ and emit MERGE_MAP.md.

Retired configs are moved, not deleted: their reportTypes are already posted to the KAM
test env, so they stay traceable until they are de-listed from the external catalogue.

Usage:  python3 retire_merged.py [--dry-run]
"""

import json
import os
import shutil
import sys

from merge_lib import ROOT, load

RETIRED_DIR = os.path.join(ROOT, "_retired")

# Filters a caller must now pass to reproduce a retired report's exact row set, because
# the merged template dropped a guard that was not shared by every family member.
EXTRA_FILTERS = {
    "INTERNAL_PERF_RR_DISPLAY_PAGE_TYPE": "page_type NOT IN ('', 'NA')",
    "INTERNAL_PERF_SEARCH_QUERY_RR_DISPLAY": "keyword NOT IN ('')",
    "INTERNAL_PERF_SEARCH_QUERY_RR_DISPLAY_AD_UNIT": "keyword NOT IN ('')",
    "INTERNAL_PERF_CATEGORY_RR": "category_l1 NOT IN ('') and page_type NOT IN ('', 'NA')",
    "INTERNAL_PERF_SEARCH_QUERY_RR_PLA": "keyword NOT IN ('')",
    "INTERNAL_PERF_SEARCH_QUERY_RR_BUCKETS": "keyword NOT IN ('')",
    "INTERNAL_PERF_RR_BY_PAGE_DISPLAY": "page_type NOT IN ('', 'NA')",
    "INTERNAL_PERF_BU_REQUESTS_DISPLAY": "page_type NOT IN ('', 'NA')",
    "INTERNAL_PERF_MERCHANT_KEYWORD":
        "campaign_type = 'performance' and campaign_subtype IN ('os_ads_search', 'smart_shopping')",
    "INTERNAL_PERF_CAMPAIGN_PERF_DAILY":
        "campaign_type IN ('PERFORMANCE', 'INVENTORY', 'OFFSITE'), and group by date",
    "INTERNAL_PERF_BUDGET_CHANGES": "action_type_id = 17",
    "INTERNAL_PERF_CAMPAIGN_STATUS_CHANGES": "action_type_id = 16",
    "INTERNAL_PERF_PRODUCT_SELECTION_CHANGES": "action_type_id IN (50, 51)",
    "INTERNAL_PERF_CAMPAIGN_KW_TARGETED": "is_negative = 0",
    "INTERNAL_PERF_CAMPAIGN_KW_NEGATIVE": "is_negative = 1",
    "INTERNAL_PERF_CAMPAIGN_NETWORKS_BY_ID":
        "filter internal_campaign_id instead of campaign_id",
    "INTERNAL_PERF_BU_REQUESTS_PLA": "group by date",
    "INTERNAL_PERF_RR_HOURLY": "group by hour",
    "INTERNAL_PERF_RR_HOURLY_AD_UNIT": "group by ad_unit",
    "INTERNAL_PERF_STORE_LEVEL_RR": "group by store_id, category, day, hour",
    "INTERNAL_PERF_KW_REQUEST_VOLUME": "keyword NOT IN (''), request days_with_requests",
    "INTERNAL_PERF_MERCHANT_CATEGORY_CPC":
        "use category_l1_raw / l2_raw / l3_raw for un-normalised category values",
}


def collect():
    plan = []
    for wave in ("merge_wave1", "merge_wave2", "merge_wave3"):
        mod = __import__(wave)
        for spec in mod.SPECS:
            for old in spec["absorbs"]:
                if old == spec["path"]:
                    continue  # merged in place
                plan.append((old, spec))
    return plan


def main():
    dry = "--dry-run" in sys.argv
    plan = collect()
    os.makedirs(RETIRED_DIR, exist_ok=True)

    rows = []
    for old_rel, spec in plan:
        old_path = os.path.join(ROOT, old_rel)
        moved = not os.path.exists(old_path)
        if moved and not os.path.exists(
                os.path.join(RETIRED_DIR, os.path.basename(old_rel))):
            print(f"  MISSING (neither in place nor retired): {old_rel}")
            continue
        # load() falls back to _retired/, so the map still regenerates on a re-run
        old = load(old_rel)
        rows.append({
            "old_type": old["reportType"],
            "old_external": old.get("externalReportType", ""),
            "old_path": old_rel,
            "new_type": spec["reportType"],
            "new_external": spec["externalReportType"],
            "new_path": spec["path"],
        })
        if not dry and not moved:
            shutil.move(old_path, os.path.join(RETIRED_DIR, os.path.basename(old_rel)))

    rows.sort(key=lambda r: (r["new_type"], r["old_type"]))

    lines = [
        "# MERGE_MAP — retired report → its replacement",
        "",
        "Generated by `scripts/retire_merged.py`. Every retired config is in",
        "`kam_report_configs/_retired/`; its reportType is still posted to the KAM test env",
        "and must be de-listed from the external catalogue separately.",
        "",
        "**Read the `Caller must now` column before switching a call site.** Where it is",
        "empty the merged report is a drop-in: request the same columns and you get the same",
        "rows. Where it is populated, the merged template dropped a guard that only some",
        "family members carried, so the caller has to supply it as a filter (or pick the",
        "grouping that reproduces the old grain).",
        "",
        "| Retired reportType | External name | Replaced by | New external name | Caller must now |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['old_type']}` | `{r['old_external']}` | `{r['new_type']}` | "
            f"`{r['new_external']}` | {EXTRA_FILTERS.get(r['old_type'], '—')} |"
        )

    by_new = {}
    for r in rows:
        by_new.setdefault(r["new_type"], []).append(r["old_type"])
    lines += ["", "## Totals", "",
              f"- {len(rows)} configs retired into {len(by_new)} merged reports"]

    out = os.path.join(ROOT, "MERGE_MAP.md")
    if not dry:
        with open(out, "w") as fh:
            fh.write("\n".join(lines) + "\n")
    print(("[dry-run] " if dry else "") + f"{len(rows)} retired into {len(by_new)} merged reports")
    print(("[dry-run] " if dry else "") + f"wrote {os.path.relpath(out, ROOT)}")


if __name__ == "__main__":
    main()
